### ISSUE TITLE
Drupal module development

### ISSUE THREAD

**Issue by mlowens** [rockfordweb/talks#11]
Your name: Mike Owens

Your idea: I'd like to show off some of the custom Drupal modules used on mfgday.com. Drupal has a particular way to do things, from routing to querying to forms. This will be a brief overview of these concepts and how to get started writing Drupal modules.

Approx length: 15 minutes (Though I could certainly extend it if there's interest.)

**Comment by jacobroufa** [comment]
Woo! This looks great Mike. There's sure to be enough people around using Drupal to build things -- it'll be nice to get some first-hand insight into what it takes to use it properly!

**Comment by jacobroufa** [comment]
Excited to see this presentation tonight!
