### ISSUE TITLE
Community Linked Data Network Map

### ISSUE THREAD

**Issue by asteriusj** [rockfordweb/talks#12]
https://github.com/asteriusj/foafiaf

**Comment by asteriusj** [comment]
Your name: Jeff Stewart

Your topic request: A community open source project that may pique your interest, I hope! FOAFIAF: Friend Of A Friend Is A Friend - A community network mapping capability levergaing RDF Datasets for Social Graph visualization and analysis https://foafiaf-asteriusj.c9users.io/

**Comment by jacobroufa** [comment]
Hey Jeff, we're excited for you and @michaeldhopkins to present this evening!
