### ISSUE TITLE
Ampify

### ISSUE THREAD

**Issue by mxedm** [rockfordweb/talks#3]
Your name: d maurer

Your idea: Because I'm lazy I decided to make something in PHP to make my poems/stories Accelerated Mobile Page. I am also a hack so I have no idea what I'm doing. It seems to work in that it creates valid AMP pages, but I don't know. So maybe somebody has some neat idea how to make it better? 

Is this a real topic?  I have no idea.

Approx length: 3, if that.

**Comment by jacobroufa** [comment]
Awesome! This is perfect Dan, especially because we have recent context given Michael's past talk on AMP. Thanks for obliging my call for talks! 🎉 🎉

**Comment by mxedm** [comment]
That's why I made the thing. :-)
