### ISSUE TITLE
Don't get hacked.

### ISSUE THREAD

**Issue by MrChrisWeinert** [rockfordweb/talks#7]
Your name: Chris Weinert

Your idea: I'm going to do a security-related presentation. I'll talk about some of the ways a hacker will attempt to gain access to a system, and hopefully show a demo to go with it. I'll also talk about ways to help mitigate these types of attacks. 

Approx length: 20 minutes?

**Comment by jacobroufa** [comment]
Very cool, Chris. Looking forward to this!

**Comment by jacobroufa** [comment]
Chris, if you can keep this to 15 minutes or less, we'd love to have you present this on Tuesday!
