### ISSUE TITLE
An Example of Google Languages

### ISSUE THREAD

**Issue by ghost** [rockfordweb/talks#8]
Your name: Ross Albertson

Your idea: I have a simple web app to demo, using both Go and Dart. It uses REST/JSON to communicate between the 2 languages, plus it incorporates a generated user interface and a client-side class.

Approx length: 20 minutes

**Comment by jacobroufa** [comment]
Ross, if you can keep this to 15 minutes or less, we'd love to see you present this on Tuesday! Thanks for the submission! :)

**Comment by jacobroufa** [comment]
Excited to see this presentation tonight!
